os: linux
dist: xenial
language: python
python: 3.8

jobs:
  include:
    # Test on Windows
    - env:
        - TOXENV=py38
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
      os: windows
      language: shell
      before_install:
        - choco install python --version=3.8

install: pip install tox

script: tox
